export const APP_PACKAGE_WIDGET_KINDS = [
  'assistantChat',
  'healthConnect',
  'schemaEditor',
  'widgetCatalog',
  'postCard',
  'pollCard',
  'linkPreview',
  'feedList',
  'kanbanBoard',
  'smartCapture',
  'chartBlock',
  'mediaBlock',
  'videoPlayer',
  'cameraScanner',
  'mapBlock',
  'locationMap',
  'sensorReadout',
  'formCard',
  'checklistCard',
  'calendarBlock',
  'notificationScheduler',
  'contactPicker',
  'calendarEvent',
  'biometricGate',
  'healthKitStatus',
  'speechTool',
  'timelineBlock',
  'galleryGrid',
  'dataTable',
  'permissionCard',
  'filePicker',
  'fileExport',
  'providerStatus',
  'themePreview',
  'themeDensitySelector',
  'aiProviderSettings',
  'dataHomeSettings',
  'scientificCalculator',
  'audioLoopPlayer',
  'foodHero',
  'useFirstCarousel',
  'mealTimeline',
  'recipeCard',
  'receiptReviewCard',
  'pantryShelf',
  'askFoodBar',
] as const;

export type AppPackageWidgetKind = typeof APP_PACKAGE_WIDGET_KINDS[number];

export const APP_PACKAGE_WIDGET_KIND_SET = new Set<string>([...APP_PACKAGE_WIDGET_KINDS]);

export function isAppPackageWidgetKind(value: unknown): value is AppPackageWidgetKind {
  return typeof value === 'string' && APP_PACKAGE_WIDGET_KIND_SET.has(value);
}
