name: OpenSSF Scorecard

on:
  branch_protection_rule:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 1"

jobs:
  analysis:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.4.4
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results-${{ github.run_id }}
          path: scorecard-results.sarif
          if-no-files-found: error
